# Generated by Django 4.2.5 on 2023-10-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentuser_is_student_teacheruser_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipteacheruser',
            name='class_membership',
        ),
        migrations.RemoveField(
            model_name='membershipteacheruser',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='MembershipStudentUser',
        ),
        migrations.DeleteModel(
            name='MembershipTeacherUser',
        ),
    ]
