# Generated by Django 4.2.5 on 2023-10-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_classmembership_alter_course_class_membership_and_more'),
        ('users', '0004_remove_membershipteacheruser_class_membership_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassMembership',
        ),
    ]
