# Generated by Django 4.2.5 on 2023-12-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_classmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
