# Generated by Django 4.2.5 on 2023-10-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.classmembership'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.classmembership'),
        ),
    ]
