# Generated by Django 4.2.5 on 2023-10-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_studentuser_membership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipstudentuser',
            name='class_membership',
        ),
        migrations.RemoveField(
            model_name='membershipstudentuser',
            name='student',
        ),
        migrations.RemoveField(
            model_name='membershipteacheruser',
            name='class_membership',
        ),
        migrations.RemoveField(
            model_name='membershipteacheruser',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClassMembership',
        ),
        migrations.DeleteModel(
            name='MembershipStudentUser',
        ),
        migrations.DeleteModel(
            name='MembershipTeacherUser',
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.DeleteModel(
            name='TeacherUser',
        ),
    ]
