# Generated by Django 4.2.5 on 2023-10-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='taglession',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
