# Generated by Django 4.2.5 on 2023-10-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_delete_status_taglession_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='factory',
        ),
    ]
