# Generated by Django 4.2.5 on 2023-10-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_rename_course_course_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
