# Generated by Django 4.2.5 on 2023-10-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_course_class_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lession',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taglession',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taglession',
            name='name',
        ),
        migrations.AddField(
            model_name='taglession',
            name='lession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lession'),
        ),
        migrations.AddField(
            model_name='taglession',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.tag'),
        ),
    ]
