# Generated by Django 4.2.5 on 2023-10-13 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_tag_remove_lession_tag_remove_taglession_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagLessionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='TagLessionExameCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.RenameField(
            model_name='lession',
            old_name='category',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='lessionexam',
            old_name='category',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='lessionexam',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.tag'),
        ),
        migrations.DeleteModel(
            name='TagLession',
        ),
        migrations.AddField(
            model_name='taglessionexamecourse',
            name='lessionexam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lessionexam'),
        ),
        migrations.AddField(
            model_name='taglessionexamecourse',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.tag'),
        ),
        migrations.AddField(
            model_name='taglessioncourse',
            name='lession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lession'),
        ),
        migrations.AddField(
            model_name='taglessioncourse',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.tag'),
        ),
    ]
