# Generated by Django 4.2.5 on 2023-10-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_taglessioncourse_taglessionexamecourse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseClassMembership',
        ),
    ]
