# Generated by Django 4.2.5 on 2023-10-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_delete_courseclassmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lession',
            name='video',
        ),
        migrations.AddField(
            model_name='lession',
            name='linkvideo',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lession',
            name='linkredirect',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessionexam',
            name='images',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessionexam',
            name='linkredirect',
            field=models.CharField(blank=True, null=True),
        ),
    ]
