# Generated by Django 4.2.5 on 2023-10-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_remove_lession_video_lession_linkvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lession',
            name='images',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessionexam',
            name='video',
            field=models.CharField(blank=True, null=True),
        ),
    ]
