# Generated by Django 4.2.5 on 2023-10-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_course_created_at_course_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessionexam',
            old_name='video',
            new_name='linkvideo',
        ),
    ]
