# Generated by Django 4.2.5 on 2023-10-16 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_membershipteacheruser_class_membership_and_more'),
        ('course', '0020_rename_video_lessionexam_linkvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTeacherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classmembership')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.factory')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacheruser')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipStudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classmembership')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.factory')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studentuser')),
            ],
        ),
    ]
