# Generated by Django 4.2.5 on 2023-10-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_membershipteacheruser_membershipstudentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.factory')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='class_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.classmembership'),
        ),
        migrations.AlterField(
            model_name='membershipstudentuser',
            name='class_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.classmembership'),
        ),
        migrations.AlterField(
            model_name='membershipteacheruser',
            name='class_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.classmembership'),
        ),
    ]
