# Generated by Django 4.2.5 on 2023-10-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_remove_sessiontimelessionexam_lessionexam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessionexam',
            name='session',
        ),
        migrations.AddField(
            model_name='lessionexam',
            name='timeend',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessionexam',
            name='timestart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SessionTimeLessionExam',
        ),
    ]
