# Generated by Django 4.2.5 on 2023-12-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_danhmuctag_chuongtag_lession_chuongtag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chuongtag',
            name='danhmuctag',
        ),
        migrations.DeleteModel(
            name='DanhMucTag',
        ),
    ]
