# Generated by Django 4.2.5 on 2023-12-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_alter_chuongtag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuongtag',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
