# Generated by Django 4.2.5 on 2023-12-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_chuongtag_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuongtag',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='chuongtag',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
