# Generated by Django 4.2.5 on 2023-12-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_alter_chuongtag_description_alter_chuongtag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuongtag',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
