# Generated by Django 4.2.5 on 2023-12-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_remove_lession_images_remove_lession_linkredirect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lession',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lessionexam',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
