# Generated by Django 4.2.5 on 2023-12-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_lession_pdf_lessionexam_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessionTracNghiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chuongTag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chuongtag')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='LessionSubTracNghiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('solutionA', models.CharField(max_length=100, null=True)),
                ('solutionB', models.CharField(max_length=100, null=True)),
                ('solutionC', models.CharField(max_length=100, null=True)),
                ('solutionD', models.CharField(max_length=100, null=True)),
                ('solutionTrue', models.CharField(max_length=100, null=True)),
                ('vitrisapxep', models.IntegerField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lessionTracNghiem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lessiontracnghiem')),
            ],
        ),
    ]
