# Generated by Django 4.2.5 on 2023-12-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_lessiontracnghiem_lessionsubtracnghiem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessionsubtracnghiem',
            old_name='name',
            new_name='nametracnghiem',
        ),
    ]
