apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app-deployment
  namespace: course2023
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-app
  template:
    metadata:
      labels:
        app: course-app
    spec:
      containers:
      - name: course-app
        image: dangnguyensonia/course2023master:v5.0
        env:
        - name: DB_HOST
          value: "db-removerelicaset-postgresql"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: course-app-service
  namespace: course2023
spec:
  selector:
    app: course-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: course-ingress
  namespace: course2023
spec:
  ingressClassName: nginx
  rules:
  - host: course2023.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: course-app-service
            port:
              number: 8000
