apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-sync-master
  namespace: course2023
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs-retain
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  postgres-data-sync-master-pv
  namespace:  course2023
  labels:
    type: local
spec:
  storageClassName: nfs-retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/mnt/nfs/postgres-data-sync-master-pv"
    server: 192.168.10.165