apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: course2023
  labels:
    app: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
      - name: postgresql
        image: postgres:9.6.2-alpine
        env:
        - name: POSTGRES_USER
          value: course
        - name: POSTGRES_DB
          value: course
        - name: POSTGRES_PASSWORD
          value: course
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgresql-storage
    persistentVolumeClaim:
      claimName: postgresql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: course2023
  labels:
    app: course
spec:
  ports:
  - port: 5432
  selector:
    app: course
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  namespace: course2023
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: course2023
  labels:
    type: local
spec:
  storageClassName: nfs-retain
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: "/mnt/nfs/postgresql"
    server: 192.168.10.165
