apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-slave
  namespace: course2023
  labels:
    app: postgres-slave
spec:
  selector:
    matchLabels:
      app: postgres-slave
  serviceName: postgres-slave
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-slave
    spec:
      initContainers:
      - name: busybox
        image: busybox
        command:
        - sh
        - -c
        - "cp /var/config/postgresql.conf /var/lib/postgresql/data/postgresql.conf && cp /var/config/recovery.conf /var/lib/postgresql/data/recovery.conf"
        - "echo 'primary_slot_name = \"$PRIMARY_SLOT_NAME\"' > /var/config/recovery.conf"
        env:
        - name: PRIMARY_SLOT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
        - mountPath: /var/config/postgresql.conf
          subPath: postgresql.conf
          name: postgres-slave-configmap
        - mountPath: /var/config/recovery.conf
          subPath: recovery.conf
          name: postgres-slave-configmap
      containers:
      - name: postgres
        image: postgres:11
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgre-account
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-slave-configmap
        configMap:
          name: postgres-slave-configmap
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-sync-master

