# Generated by Django 4.2.5 on 2023-10-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='factory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='is_notsubcategory',
            field=models.BooleanField(default=True),
        ),
    ]
