# Generated by Django 4.2.5 on 2023-10-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_factory_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_notsubcategory',
            field=models.BooleanField(default=False),
        ),
    ]
