# Generated by Django 4.2.5 on 2023-10-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_is_notsubcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lession',
            new_name='Blogs',
        ),
    ]
