# Generated by Django 4.2.5 on 2023-10-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
